import { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: "marjoki-strawberry-100g",
    slug: "strawberry",
    name: "Marjoki Strawberry Xylitol Pastilles",
    shortName: "Strawberry",
    flavour: "Strawberry",
    description: "A soft berry profile in a sugar-free after-meal pastille format.",
    priceGbp: 8.99,
    size: "100g pouch",
    xylitolPercent: 92,
    category: "flavour",
    image: "/brand/products/strawberry-100g.png",
    accent: "strawberry",
    veganFriendly: true,
    glutenFree: true,
    soyFree: true,
    lactoseFree: true,
    milkFree: true,
    ingredients: [
      "Xylitol (92%)",
      "Carboxymethylcellulose",
      "Calcium phosphate",
      "Natural flavour",
      "Magnesium stearate",
      "Lingonberry juice powder (colour)",
    ],
    nutritionPer100g: {
      energy: "1010 kJ / 242 kcal",
      fat: "2g",
      saturates: "2g",
      carbs: "92g",
      sugars: "0g",
      protein: "0g",
      salt: "0g",
    },
    usage: ["Take 1-2 pastilles after meals.", "Use up to 6 pastilles per day."],
    safety: [
      "Excessive consumption may produce laxative effects.",
      "Store dry at room temperature.",
    ],
    factualNotes: ["Made in Finland in Kitee by family-owned Narskuttelu."],
  },
  {
    id: "marjoki-mango-100g",
    slug: "mango",
    name: "Marjoki Mango Xylitol Pastilles",
    shortName: "Mango",
    flavour: "Mango",
    description: "Bright mango flavour with a clean after-meal habit profile.",
    priceGbp: 8.99,
    size: "100g pouch",
    xylitolPercent: 92,
    category: "flavour",
    image: "/brand/products/mango-100g.png",
    accent: "mango",
    veganFriendly: true,
    glutenFree: true,
    soyFree: true,
    lactoseFree: true,
    milkFree: true,
    ingredients: [
      "Xylitol (92%)",
      "Carboxymethylcellulose",
      "Calcium phosphate",
      "Magnesium stearate",
      "Natural flavour",
    ],
    usage: ["Take 1-2 pastilles after meals.", "Use up to 6 pastilles per day."],
    safety: [
      "Excessive consumption may produce laxative effects.",
      "Store dry at room temperature.",
      "Approx. 1100 pieces per 1kg based on supplier guidance.",
    ],
    factualNotes: ["Made in Finland in Kitee by family-owned Narskuttelu."],
  },
  {
    id: "marjoki-raspberry-100g",
    slug: "raspberry",
    name: "Marjoki Raspberry Xylitol Pastilles",
    shortName: "Raspberry",
    flavour: "Raspberry",
    description: "Balanced raspberry notes with a gentle, not-too-sweet finish.",
    priceGbp: 8.99,
    size: "100g pouch",
    xylitolPercent: 92,
    category: "flavour",
    image: "/brand/products/raspberry-100g.png",
    accent: "raspberry",
    veganFriendly: true,
    glutenFree: true,
    soyFree: true,
    lactoseFree: true,
    milkFree: true,
    ingredients: [
      "Xylitol (92%)",
      "Carboxymethylcellulose",
      "Calcium phosphate",
      "Magnesium stearate",
      "Natural flavours",
      "Lingonberry juice powder (colour)",
    ],
    usage: ["Take 1-2 pastilles after meals.", "Use up to 6 pastilles per day."],
    safety: [
      "Excessive consumption may produce laxative effects.",
      "Store dry at room temperature.",
      "Approx. 800 mg xylitol per pastille.",
    ],
    factualNotes: ["Made in Finland in Kitee by family-owned Narskuttelu."],
  },
  {
    id: "marjoki-blueberry-100g",
    slug: "blueberry",
    name: "Marjoki Blueberry Xylitol Pastilles",
    shortName: "Blueberry",
    flavour: "Blueberry",
    description: "Blueberry-forward flavour with a smooth after-meal finish.",
    priceGbp: 8.99,
    size: "100g pouch",
    xylitolPercent: 88,
    category: "flavour",
    image: "/brand/products/blueberry-100g.png",
    accent: "blueberry",
    veganFriendly: true,
    glutenFree: true,
    soyFree: true,
    lactoseFree: true,
    milkFree: true,
    ingredients: [
      "Xylitol (88%)",
      "Berry juice powder (6%)",
      "Carboxymethylcellulose",
      "Calcium phosphate",
      "Calcium carbonate",
      "Magnesium stearate",
    ],
    nutritionPer100g: {
      energy: "1010 kJ / 242 kcal",
      fat: "2g",
      saturates: "2g",
      carbs: "88g",
      sugars: "0g",
      protein: "0g",
      salt: "0g",
    },
    usage: ["Take 1-2 pastilles after meals.", "Use up to 6 pastilles per day."],
    safety: [
      "Excessive consumption may produce laxative effects.",
      "Store dry at room temperature.",
    ],
    factualNotes: ["Made in Finland in Kitee by family-owned Narskuttelu."],
  },
  {
    id: "marjoki-passionfruit-100g",
    slug: "passionfruit",
    name: "Marjoki Passionfruit Xylitol Pastilles",
    shortName: "Passionfruit",
    flavour: "Passionfruit",
    description: "A tropical passionfruit profile designed for daily after-meal use.",
    priceGbp: 8.99,
    size: "100g pouch",
    xylitolPercent: 92,
    category: "flavour",
    image: "/brand/products/passionfruit-100g.png",
    accent: "passionfruit",
    veganFriendly: true,
    glutenFree: true,
    soyFree: true,
    lactoseFree: true,
    milkFree: true,
    ingredients: [
      "Xylitol (92%)",
      "Carboxymethylcellulose",
      "Calcium phosphate",
      "Magnesium stearate",
      "Natural flavour",
    ],
    nutritionPer100g: {
      energy: "1010 kJ / 242 kcal",
      fat: "2g",
      saturates: "2g",
      carbs: "92g",
      sugars: "0g",
      protein: "0g",
      salt: "0g",
    },
    usage: ["Take 1-2 pastilles after meals.", "Use up to 6 pastilles per day."],
    safety: [
      "Excessive consumption may produce laxative effects.",
      "Store dry at room temperature.",
      "Approx. 800 mg xylitol + 24 mg calcium phosphate per pastille.",
      "Approx. 110-120 pastilles per 100g bag.",
    ],
    factualNotes: ["Made in Finland in Kitee by family-owned Narskuttelu."],
  },
  {
    id: "marjoki-discovery-pack",
    slug: "discovery-pack",
    name: "Marjoki Discovery Pack",
    shortName: "Discovery Pack",
    flavour: "Mixed",
    description: "A mixed-flavour launch pack designed for first-time Marjoki buyers.",
    priceGbp: 7.49,
    size: "20g pouch",
    xylitolPercent: null,
    category: "discovery-pack",
    image: "/brand/products/discovery-pack-20g.png",
    accent: "blueberry",
    ingredients: ["Mixed launch flavours from current Marjoki range."],
    usage: ["Try after meals to discover your preferred flavour profile."],
    safety: [
      "Excessive consumption may produce laxative effects.",
      "Store dry at room temperature.",
    ],
    factualNotes: ["Early-stage discovery format. Full flavour pouches sold separately."],
  },
];

export const flavourProducts = products.filter((product) => product.category === "flavour");
export const discoveryPack = products.find((product) => product.category === "discovery-pack");

export const getProductBySlug = (slug: string) =>
  products.find((product) => product.slug === slug);
